'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, LockKeyhole, MapPin, ShieldCheck, Sparkles, WalletCards, Zap } from 'lucide-react'

const steps = [
  { title: 'Fondeo', text: 'El comprador deposita USDC. El dinero queda bloqueado y protegido.', icon: WalletCards },
  { title: 'Despacho en Flota', text: 'El vendedor envía el producto con seguimiento entre ciudades.', icon: MapPin },
  { title: 'Liberación con PIN', text: 'El comprador confirma la recepción con un PIN seguro.', icon: LockKeyhole },
]
const comparisons = {
  Altipay: ['Escrow protegido', 'Comisión clara', 'PIN de liberación', 'Entre ciudades'],
  Bancos: ['Intermediario', 'Comisiones altas', 'Días de espera', 'Horarios limitados'],
  'Tigo Money': ['Sin escrow', 'Límites variables', 'Sin protección comercial', 'Red propia'],
  Efectivo: ['Riesgo personal', 'Sin comprobante', 'Sin respaldo', 'Solo presencial'],
}

export default function LandingPage() {
  const [activeStep, setActiveStep] = useState(0)
  const [activeCompare, setActiveCompare] = useState('Altipay')
  const [amount, setAmount] = useState(2500)
  const vipSavings = useMemo(() => Math.max(0, Math.round(amount * 0.028)), [amount])

  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Zap className="size-4 fill-current" /></div><span className="text-lg font-semibold tracking-tight">altipay</span></div><div className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#como-funciona" className="hover:text-foreground">Cómo funciona</a><a href="#comparativa" className="hover:text-foreground">Comparativa</a><a href="#ahorro" className="hover:text-foreground">VIP Unlock</a></div><div className="flex items-center gap-2"><Link href="/dashboard" className="rounded-lg border border-border px-4 py-2 text-sm font-medium hover:border-primary/60">Abrir app</Link></div></nav>
    <section className="relative mx-auto max-w-7xl px-5 pb-24 pt-16 sm:px-8 sm:pt-24"><div className="absolute right-0 top-16 -z-0 hidden h-72 w-72 rounded-full bg-primary/10 blur-3xl lg:block" /><div className="relative z-10 max-w-4xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/5 px-3 py-1.5 text-xs font-medium text-primary"><span className="size-1.5 rounded-full bg-primary" />Comercio protegido para Bolivia</div><h1 className="max-w-4xl text-balance text-5xl font-semibold leading-[1.02] tracking-[-0.06em] sm:text-7xl lg:text-[88px]">Comercio seguro entre <span className="text-primary">La Paz, Cochabamba</span> y Santa Cruz.</h1><p className="mt-7 max-w-2xl text-pretty text-lg leading-8 text-muted-foreground">Altipay mantiene tu dinero protegido hasta que el producto llega a tus manos. Compra y vende con confianza, desde cualquier ciudad.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/dashboard" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground">Crear mi primer escrow <ArrowRight className="size-4" /></Link><a href="#como-funciona" className="inline-flex h-12 items-center justify-center rounded-xl border border-border px-5 text-sm font-medium hover:border-primary/50">Ver cómo funciona</a></div></div><div className="mt-20 grid gap-px border border-border bg-border sm:grid-cols-3"><Metric value="98.6%" label="transacciones completadas" /><Metric value="3 ciudades" label="conectadas por flota" /><Metric value="$0" label="reembolsos injustos" /></div></section>
    <section id="como-funciona" className="border-y border-border bg-card/40"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionIntro eyebrow="El circuito Altipay" title="Tu dinero solo se mueve cuando el trato se cumple." text="Una protección simple para el comercio entre personas y negocios." /><div className="mt-12 grid gap-3 lg:grid-cols-3">{steps.map((step, index) => { const Icon = step.icon; return <button key={step.title} onClick={() => setActiveStep(index)} className={`group relative border p-6 text-left transition ${activeStep === index ? 'border-primary bg-primary/[0.07]' : 'border-border bg-background hover:border-primary/40'}`}><span className="font-mono text-xs text-primary">0{index + 1}</span><Icon className="mt-12 size-6 text-primary" /><h3 className="mt-7 text-xl font-semibold">{step.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{step.text}</p><div className={`mt-8 h-1 transition ${activeStep === index ? 'bg-primary' : 'bg-muted'}`} /></button> })}</div><div className="mt-4 border border-primary/20 bg-primary/5 p-5 text-sm text-muted-foreground"><span className="font-semibold text-primary">Paso {activeStep + 1}:</span> {steps[activeStep].text}</div></div></section>
    <section id="comparativa" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionIntro eyebrow="Una forma más segura" title="Menos incertidumbre. Más comercio." text="Compara la experiencia de mover tu dinero con las alternativas tradicionales." /><div className="mt-10 flex flex-wrap gap-2">{Object.keys(comparisons).map((name) => <button key={name} onClick={() => setActiveCompare(name)} className={`rounded-lg px-4 py-2 text-sm transition ${activeCompare === name ? 'bg-primary text-primary-foreground' : 'border border-border text-muted-foreground hover:text-foreground'}`}>{name}</button>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(comparisons).map(([name, items]) => <div key={name} className={`border p-6 ${name === activeCompare ? 'border-primary bg-primary/[0.06]' : 'border-border bg-card'}`}><div className="flex items-center justify-between"><h3 className="font-semibold">{name}</h3>{name === 'Altipay' && <ShieldCheck className="size-4 text-primary" />}</div><ul className="mt-6 space-y-4">{items.map((item) => <li key={item} className="flex items-center gap-2 text-sm text-muted-foreground"><Check className="size-4 text-primary" />{item}</li>)}</ul></div>)}</div></section>
    <section id="ahorro" className="border-y border-border bg-card/40"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_0.9fr] lg:items-center"><div><SectionIntro eyebrow="VIP Unlock" title="Calcula cuánto puedes ahorrar." text="Con VIP Unlock, tus comisiones bajan mientras más comercias. Mantén más valor en cada transacción." /><div className="mt-9"><label htmlFor="amount" className="flex justify-between text-sm font-medium"><span>Valor de tu operación</span><span className="font-mono text-primary">${amount.toLocaleString('en-US')} USDC</span></label><input id="amount" type="range" min="250" max="10000" step="50" value={amount} onChange={(event) => setAmount(Number(event.target.value))} className="mt-5 w-full accent-[var(--primary)]" /></div></div><div className="border border-primary/30 bg-background p-7"><div className="flex items-center gap-2 text-sm font-medium text-primary"><Sparkles className="size-4" /> VIP Unlock activo</div><div className="mt-8 flex items-end justify-between border-b border-border pb-6"><div><p className="text-xs text-muted-foreground">Ahorro estimado</p><p className="mt-2 text-5xl font-semibold tracking-tight text-primary">${vipSavings}</p></div><span className="pb-1 text-xs text-muted-foreground">por operación</span></div><div className="space-y-3 pt-5 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Comisión estándar</span><span>{(amount * .035).toFixed(2)} USDC</span></div><div className="flex justify-between"><span className="text-muted-foreground">Con VIP Unlock</span><span className="text-primary">{(amount * .007).toFixed(2)} USDC</span></div></div><button className="mt-7 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary text-sm font-semibold text-primary-foreground">Desbloquear VIP <ArrowRight className="size-4" /></button></div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 sm:flex-row sm:items-center sm:justify-between sm:px-8"><div><p className="font-semibold">altipay</p><p className="mt-1 text-xs text-muted-foreground">Comercio protegido, sin fronteras.</p></div><Link href="/dashboard" className="text-sm text-primary hover:underline">Entrar al dashboard <ArrowRight className="ml-1 inline size-3.5" /></Link></footer>
  </main>
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="bg-card p-5"><p className="text-2xl font-semibold tracking-tight text-primary">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div> }
function SectionIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h2 className="mt-4 text-balance text-3xl font-semibold tracking-[-0.04em] sm:text-5xl">{title}</h2><p className="mt-4 text-pretty text-sm leading-7 text-muted-foreground sm:text-base">{text}</p></div> }
