import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";

dotenv.config();

async function main() {
  console.log("\n📦 [AltiPay Protocol] Exportando ABIs y Direcciones de Contratos...");

  const artifactsDir = path.join(__dirname, "../artifacts/contracts");
  const escrowArtifactPath = path.join(artifactsDir, "AltiPayEscrow.sol/AltiPayEscrow.json");
  const usdcArtifactPath = path.join(artifactsDir, "MockUSDC.sol/MockUSDC.json");

  if (!fs.existsSync(escrowArtifactPath) || !fs.existsSync(usdcArtifactPath)) {
    console.error("❌ No se encontraron los artefactos compilados. Ejecuta 'npm run compile' primero.");
    process.exit(1);
  }

  const escrowArtifact = JSON.parse(fs.readFileSync(escrowArtifactPath, "utf8"));
  const usdcArtifact = JSON.parse(fs.readFileSync(usdcArtifactPath, "utf8"));

  const contractsData = {
    // 🔴 Avalanche Fuji Testnet (Chain ID 43113)
    43113: {
      name: "Avalanche Fuji",
      AltiPayEscrow: {
        address: process.env.ESCROW_FUJI_ADDRESS || "0x0000000000000000000000000000000000000000",
        abi: escrowArtifact.abi,
      },
      MockUSDC: {
        address: process.env.USDC_FUJI_ADDRESS || "0x0000000000000000000000000000000000000000",
        abi: usdcArtifact.abi,
      },
    },
    // 🟡 HashKey Chain Testnet (Chain ID 133)
    133: {
      name: "HSK Testnet",
      AltiPayEscrow: {
        address: process.env.ESCROW_HSK_ADDRESS || "0x0000000000000000000000000000000000000000",
        abi: escrowArtifact.abi,
      },
      MockUSDC: {
        address: process.env.USDC_HSK_ADDRESS || "0x0000000000000000000000000000000000000000",
        abi: usdcArtifact.abi,
      },
    },
    // 🟡 HashKey Chain Mainnet (Chain ID 177)
    177: {
      name: "HSK Mainnet",
      AltiPayEscrow: {
        address: process.env.ESCROW_HSK_ADDRESS || "0x0000000000000000000000000000000000000000",
        abi: escrowArtifact.abi,
      },
      MockUSDC: {
        address: process.env.USDC_HSK_ADDRESS || "0x0000000000000000000000000000000000000000",
        abi: usdcArtifact.abi,
      },
    },
    // 💻 Local Hardhat (Chain ID 31337)
    31337: {
      name: "Hardhat Local",
      AltiPayEscrow: {
        address: process.env.ESCROW_LOCAL_ADDRESS || "0x5FbDB2315678afecb367f032d93F642f64180aa3",
        abi: escrowArtifact.abi,
      },
      MockUSDC: {
        address: process.env.USDC_LOCAL_ADDRESS || "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
        abi: usdcArtifact.abi,
      },
    },
  };

  const fileContent = `/* Auto-generated by Luis Sandoval (DEV 1) - AltiPay Protocol */\nexport const deployedContracts = ${JSON.stringify(
    contractsData,
    null,
    2
  )} as const;\n\nexport type DeployedContractsType = typeof deployedContracts;\n`;

  // 1. Guardar copia en contracts/
  const contractsExportPath = path.join(__dirname, "../contracts/deployedContracts.ts");
  fs.writeFileSync(contractsExportPath, fileContent, "utf8");
  console.log(`✅ Exportado a: ${contractsExportPath}`);

  // 2. Si existe la carpeta frontend, exportar también allá para Jorge Ayala (DEV 2)
  const frontendContractsDir = path.join(__dirname, "../frontend/contracts");
  if (!fs.existsSync(frontendContractsDir)) {
    fs.mkdirSync(frontendContractsDir, { recursive: true });
  }
  const frontendExportPath = path.join(frontendContractsDir, "deployedContracts.ts");
  fs.writeFileSync(frontendExportPath, fileContent, "utf8");
  console.log(`✅ Exportado a: ${frontendExportPath} (Listo para DEV 2)`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
