'use client'

import { useMemo, useState } from 'react'
import {
  ArrowDownLeft, ArrowUpRight, Bell, Check, ChevronRight, CircleHelp, Clock3, Copy,
  ExternalLink, FileText, LayoutDashboard, LifeBuoy, Menu, MoreHorizontal, Plus,
  Search, ShieldCheck, Sparkles, Wallet, X, Zap,
} from 'lucide-react'

type Escrow = { title: string; id: string; counterparty: string; role: string; amount: string; status: string; tone: 'blue' | 'amber' | 'green'; progress: number; date: string; initials: string }

const initialEscrows: Escrow[] = [
  { title: 'MacBook Pro M3', id: 'ALT-8924', counterparty: 'jordan.merchant', role: 'Buying from', amount: '$1,850.00', status: 'In transit', tone: 'blue', progress: 68, date: 'Due Sep 18, 2026', initials: 'JM' },
  { title: 'Brand identity project', id: 'ALT-8918', counterparty: 'studio.north', role: 'Selling to', amount: '$2,400.00', status: 'Awaiting delivery', tone: 'amber', progress: 42, date: 'Due Sep 22, 2026', initials: 'SN' },
  { title: 'Custom keyboard build', id: 'ALT-8891', counterparty: 'kai.builds', role: 'Buying from', amount: '$680.00', status: 'Payment secured', tone: 'green', progress: 18, date: 'Created Sep 10, 2026', initials: 'KB' },
]
const activities = [
  { icon: ArrowDownLeft, label: 'Funds deposited', detail: 'Brand identity project', time: 'Today, 9:42 AM', amount: '+ $2,400.00', positive: true },
  { icon: ShieldCheck, label: 'Escrow secured', detail: 'Custom keyboard build', time: 'Yesterday, 4:18 PM', amount: '$680.00', positive: false },
  { icon: ArrowUpRight, label: 'Payment released', detail: 'Logo animation package', time: 'Sep 10, 2026', amount: '− $950.00', positive: false },
]

function Logo() { return <div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Zap className="size-4 fill-current" /></div><span className="text-[17px] font-semibold tracking-tight">altipay</span></div> }
function StatusPill({ tone, children }: { tone: Escrow['tone']; children: React.ReactNode }) { const style = tone === 'green' ? 'bg-emerald-400/10 text-emerald-300' : tone === 'amber' ? 'bg-amber-400/10 text-amber-300' : 'bg-sky-400/10 text-sky-300'; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-medium ${style}`}><span className="size-1.5 rounded-full bg-current" />{children}</span> }

export default function Page() {
  const [escrows, setEscrows] = useState(initialEscrows)
  const [mobileNav, setMobileNav] = useState(false)
  const [section, setSection] = useState('Overview')
  const [query, setQuery] = useState('')
  const [modal, setModal] = useState<'create' | 'wallet' | 'dispute' | null>(null)
  const [selected, setSelected] = useState<Escrow | null>(null)
  const [toast, setToast] = useState('')
  const [connected, setConnected] = useState(false)
  const [copied, setCopied] = useState(false)
  const [form, setForm] = useState({ title: '', counterparty: '', amount: '' })
  const showToast = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const filtered = useMemo(() => escrows.filter((item) => `${item.title} ${item.counterparty} ${item.id}`.toLowerCase().includes(query.toLowerCase())), [escrows, query])
  const createEscrow = () => { if (!form.title || !form.counterparty || !form.amount) return; const next: Escrow = { title: form.title, id: `ALT-${8900 + escrows.length + 1}`, counterparty: form.counterparty, role: 'Buying from', amount: `$${Number(form.amount).toLocaleString('en-US', { minimumFractionDigits: 2 })}`, status: 'Payment secured', tone: 'green', progress: 12, date: 'Created today', initials: form.counterparty.slice(0, 2).toUpperCase() }; setEscrows([next, ...escrows]); setForm({ title: '', counterparty: '', amount: '' }); setModal(null); showToast('Escrow created successfully') }
  const nav = (name: string) => { setSection(name); setMobileNav(false); if (name !== 'Overview') showToast(`${name} view selected`) }

  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[238px] flex-col border-r border-sidebar-border bg-sidebar px-4 py-5 transition-transform lg:translate-x-0 ${mobileNav ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-2"><Logo /><button onClick={() => setMobileNav(false)} className="rounded-lg p-1.5 text-muted-foreground lg:hidden" aria-label="Close navigation"><X className="size-4" /></button></div>
      <div className="mt-10 flex flex-1 flex-col"><p className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground/70">Workspace</p><nav className="space-y-1" aria-label="Primary navigation">{[['Overview', LayoutDashboard], ['My escrows', FileText], ['Wallet', Wallet], ['Disputes', LifeBuoy]].map(([label, Icon]) => <button key={label as string} onClick={() => nav(label as string)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[13px] font-medium ${section === label ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-sidebar-accent hover:text-foreground'}`}><Icon className="size-[17px]" /><span className="flex-1">{label as string}</span>{label === 'My escrows' && <span className="text-[10px]">{escrows.length}</span>}{label === 'Disputes' && <span className="rounded-md bg-amber-400/10 px-1.5 py-0.5 text-[10px] text-amber-300">1</span>}</button>)}</nav><div className="my-7 h-px bg-sidebar-border" /><p className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground/70">Resources</p><button onClick={() => showToast('Help center opened')} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[13px] text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><CircleHelp className="size-[17px]" />Help center</button><button onClick={() => showToast('You are up to date')} className="mt-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[13px] text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><Sparkles className="size-[17px]" />What&apos;s new</button></div>
      <div className="rounded-2xl border border-sidebar-border bg-sidebar-accent/50 p-3.5"><div className="mb-3 flex items-center gap-2"><div className="grid size-7 place-items-center rounded-lg bg-emerald-400/10 text-emerald-300"><ShieldCheck className="size-4" /></div><span className="text-xs font-semibold">Protected by Altipay</span></div><p className="text-[11px] leading-5 text-muted-foreground">Funds stay locked until both sides confirm.</p></div>
    </aside>
    <div className="lg:pl-[238px]"><header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-border/70 bg-background px-5 sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileNav(true)} className="rounded-lg p-2 text-muted-foreground lg:hidden" aria-label="Open navigation"><Menu className="size-5" /></button><div className="relative hidden sm:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-9 w-56 rounded-lg border border-border bg-muted/40 pl-9 pr-3 text-xs outline-none placeholder:text-muted-foreground focus:border-ring" placeholder="Search escrows..." aria-label="Search escrows" /></div></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/5 px-3 py-1.5 sm:flex"><span className="size-1.5 rounded-full bg-emerald-400" /><span className="text-[11px] font-medium text-emerald-300">Fuji Testnet</span></div><button onClick={() => showToast('No new notifications')} className="relative rounded-lg p-2 text-muted-foreground" aria-label="Notifications"><Bell className="size-[18px]" /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-primary" /></button><button onClick={() => setModal('wallet')} className="flex items-center gap-2 rounded-lg border border-border bg-muted/30 py-1.5 pl-2 pr-2.5 text-xs font-medium"><span className="grid size-6 place-items-center rounded-md bg-primary/10 text-primary"><Wallet className="size-3.5" /></span>{connected ? '0x71A4...92cD' : 'Connect wallet'}</button></div></header>
      <main className="mx-auto max-w-[1380px] px-5 py-8 sm:px-8 lg:px-10"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><span>Workspace</span><ChevronRight className="size-3" /><span className="text-foreground">{section}</span></div><h1 className="text-3xl font-semibold tracking-[-0.035em] sm:text-[34px]">Good morning, Alex<span className="text-primary">.</span></h1><p className="mt-2 text-sm text-muted-foreground">Here&apos;s what&apos;s happening with your protected payments.</p></div><button onClick={() => setModal('create')} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus className="size-4" /> Create escrow</button></div>
        {section === 'My escrows' ? <EscrowsView escrows={filtered} onSelect={setSelected} onCreate={() => setModal('create')} /> : section === 'Wallet' ? <WalletView connected={connected} onConnect={() => setModal('wallet')} onToast={showToast} /> : section === 'Disputes' ? <DisputesView onOpen={() => setModal('dispute')} /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Protected balance" value="$4,930.00" note="Across active escrows" icon={ShieldCheck} /><Metric label="Available USDC" value="$8,240.54" note="+ $1,200.00 this month" icon={Wallet} positive /><Metric label="Active escrows" value={String(escrows.length)} note="2 buying · 1 selling" icon={Clock3} /><Metric label="Trust score" value="98/100" note="Excellent standing" icon={Sparkles} positive /></section>
        <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-base font-semibold">Active escrows</h2><p className="mt-1 text-xs text-muted-foreground">Track your protected transactions</p></div><button onClick={() => nav('My escrows')} className="flex items-center gap-1 text-xs font-medium text-primary">View all <ChevronRight className="size-3.5" /></button></div><div className="space-y-3">{filtered.map((escrow) => <article key={escrow.id} onClick={() => setSelected(escrow)} className="group cursor-pointer rounded-2xl border border-border bg-card p-5 hover:border-primary/30"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-muted text-xs font-semibold text-muted-foreground">{escrow.initials}</div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{escrow.title}</h3><span className="font-mono text-[10px] text-muted-foreground">{escrow.id}</span></div><p className="mt-1 text-xs text-muted-foreground">{escrow.role} <span className="text-foreground/70">{escrow.counterparty}</span></p></div></div><div className="flex items-center justify-between gap-4 sm:justify-end"><div className="text-left sm:text-right"><p className="text-sm font-semibold">{escrow.amount}</p><p className="mt-1 text-[10px] text-muted-foreground">USDC</p></div><StatusPill tone={escrow.tone}>{escrow.status}</StatusPill><MoreHorizontal className="size-4 text-muted-foreground" /></div></div><div className="mt-5"><div className="mb-2 flex justify-between text-[11px] text-muted-foreground"><span>Escrow progress</span><span>{escrow.date}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${escrow.progress}%` }} /></div></div></article>)}{filtered.length === 0 && <div className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No escrows match your search.</div>}</div></section>
          <aside className="space-y-5"><div className="rounded-2xl border border-amber-400/20 bg-amber-400/[0.04] p-5"><div className="flex items-start justify-between"><div className="grid size-9 place-items-center rounded-xl bg-amber-400/10 text-amber-300"><LifeBuoy className="size-4" /></div><span className="rounded-full bg-amber-400/10 px-2 py-1 text-[10px] font-medium text-amber-300">Action needed</span></div><h3 className="mt-4 text-sm font-semibold">Review a potential dispute</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">A delivery window has passed. Because it was dispatched, funds won&apos;t be refunded automatically.</p><button onClick={() => setModal('dispute')} className="mt-4 flex items-center gap-1.5 text-xs font-semibold text-amber-300">Open dispute center <ExternalLink className="size-3.5" /></button></div><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Recent activity</h3><button onClick={() => showToast('Activity menu opened')} aria-label="More activity options"><MoreHorizontal className="size-4 text-muted-foreground" /></button></div><div className="mt-4 space-y-4">{activities.map(({ icon: Icon, label, detail, time, amount, positive }) => <div className="flex items-start gap-3" key={label}><div className="grid size-8 shrink-0 place-items-center rounded-lg bg-muted text-muted-foreground"><Icon className="size-3.5" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="truncate text-xs font-medium">{label}</p><span className={`whitespace-nowrap text-[11px] font-medium ${positive ? 'text-emerald-300' : ''}`}>{amount}</span></div><p className="mt-0.5 truncate text-[11px] text-muted-foreground">{detail}</p><p className="mt-1 text-[10px] text-muted-foreground/70">{time}</p></div></div>)}</div><button onClick={() => showToast('All activity loaded')} className="mt-5 flex w-full items-center justify-center gap-1 text-xs font-medium text-primary">View all activity <ChevronRight className="size-3.5" /></button></div></aside></div>
        </>}
      </main></div>
      {toast && <div role="status" className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-border bg-card px-4 py-3 text-sm shadow-2xl">{toast}</div>}
      {modal && <Modal title={modal === 'create' ? 'Create a new escrow' : modal === 'wallet' ? 'Wallet connection' : 'Dispute center'} onClose={() => setModal(null)}>{modal === 'create' && <div className="space-y-4"><Field label="What are you trading?" value={form.title} onChange={(v) => setForm({ ...form, title: v })} placeholder="e.g. Website redesign" /><Field label="Counterparty username" value={form.counterparty} onChange={(v) => setForm({ ...form, counterparty: v })} placeholder="e.g. jordan.merchant" /><Field label="Amount in USDC" value={form.amount} onChange={(v) => setForm({ ...form, amount: v })} placeholder="0.00" type="number" /><button onClick={createEscrow} className="mt-2 h-11 w-full rounded-xl bg-primary text-sm font-semibold text-primary-foreground">Create protected escrow</button></div>}{modal === 'wallet' && <div className="text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-primary/10 text-primary"><Wallet className="size-7" /></div><h3 className="mt-4 text-lg font-semibold">{connected ? 'Wallet connected' : 'Connect your wallet'}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">This demo simulates a secure wallet connection on Fuji Testnet.</p><button onClick={() => { setConnected(true); setModal(null); showToast('Wallet connected successfully') }} className="mt-6 h-11 w-full rounded-xl bg-primary text-sm font-semibold text-primary-foreground">{connected ? 'Connected' : 'Connect demo wallet'}</button></div>}{modal === 'dispute' && <div><div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Vintage camera lens</strong> was dispatched but its delivery window passed. Both parties can submit evidence before a mediator decides.</div><button onClick={() => { setModal(null); showToast('Dispute opened — evidence window started') }} className="mt-5 h-11 w-full rounded-xl bg-primary text-sm font-semibold text-primary-foreground">Start dispute review</button></div>}</Modal>}
      {selected && <Modal title={selected.title} onClose={() => setSelected(null)}><div className="space-y-4"><div className="flex items-center justify-between rounded-xl bg-muted/50 p-4"><div><p className="text-xs text-muted-foreground">Escrow amount</p><p className="mt-1 text-xl font-semibold">{selected.amount} <span className="text-xs text-muted-foreground">USDC</span></p></div><StatusPill tone={selected.tone}>{selected.status}</StatusPill></div><div className="grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl border border-border p-3"><p className="text-muted-foreground">Escrow ID</p><p className="mt-1 font-mono">{selected.id}</p></div><div className="rounded-xl border border-border p-3"><p className="text-muted-foreground">Counterparty</p><p className="mt-1">{selected.counterparty}</p></div></div><div className="rounded-xl border border-border p-4"><div className="flex justify-between text-xs"><span>Protected transaction progress</span><span>{selected.progress}%</span></div><div className="mt-3 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${selected.progress}%` }} /></div></div><button onClick={() => { setSelected(null); showToast('Confirmation recorded') }} className="h-11 w-full rounded-xl border border-primary/30 text-sm font-semibold text-primary"><Check className="mr-2 inline size-4" />Confirm milestone</button></div></Modal>}
    </div>
}

function EscrowsView({ escrows, onSelect, onCreate }: { escrows: Escrow[]; onSelect: (escrow: Escrow) => void; onCreate: () => void }) { return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 rounded-2xl border border-border bg-card p-5 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold">All protected escrows</h2><p className="mt-1 text-xs text-muted-foreground">Every transaction, milestone, and counterparty in one place.</p></div><button onClick={onCreate} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus className="size-4" /> New escrow</button></div><div className="grid gap-3">{escrows.map((escrow) => <button key={escrow.id} onClick={() => onSelect(escrow)} className="rounded-2xl border border-border bg-card p-5 text-left transition hover:border-primary/40"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-muted text-xs font-semibold text-muted-foreground">{escrow.initials}</div><div><p className="text-sm font-semibold">{escrow.title}</p><p className="mt-1 text-xs text-muted-foreground">{escrow.id} · {escrow.counterparty}</p></div></div><div className="flex items-center gap-4"><div className="text-right"><p className="text-sm font-semibold">{escrow.amount}</p><p className="text-[10px] text-muted-foreground">USDC</p></div><StatusPill tone={escrow.tone}>{escrow.status}</StatusPill><ChevronRight className="size-4 text-muted-foreground" /></div></div><div className="mt-4 flex items-center gap-3"><div className="h-1.5 flex-1 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${escrow.progress}%` }} /></div><span className="text-[11px] text-muted-foreground">{escrow.progress}%</span></div></button>)}</div></div> }
function WalletView({ connected, onConnect, onToast }: { connected: boolean; onConnect: () => void; onToast: (message: string) => void }) { return <div className="space-y-5"><div className="rounded-2xl border border-primary/20 bg-primary/[0.06] p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs text-muted-foreground">Available USDC balance</p><p className="mt-2 text-4xl font-semibold tracking-tight">$8,240.54</p><p className="mt-2 text-xs text-emerald-300">+$1,200.00 this month</p></div><button onClick={onConnect} className="h-10 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground">{connected ? 'Wallet connected' : 'Connect wallet'}</button></div></div><div className="grid gap-4 sm:grid-cols-2"><button onClick={() => onToast('Deposit flow opened')} className="rounded-2xl border border-border bg-card p-5 text-left hover:border-primary/40"><ArrowDownLeft className="size-5 text-emerald-300" /><p className="mt-4 text-sm font-semibold">Deposit USDC</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Add funds to protect a new transaction.</p></button><button onClick={() => onToast('Withdrawal flow opened')} className="rounded-2xl border border-border bg-card p-5 text-left hover:border-primary/40"><ArrowUpRight className="size-5 text-primary" /><p className="mt-4 text-sm font-semibold">Withdraw funds</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Move your available balance to your wallet.</p></button></div></div> }
function DisputesView({ onOpen }: { onOpen: () => void }) { return <div className="space-y-5"><div className="rounded-2xl border border-amber-400/20 bg-amber-400/[0.05] p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium text-amber-300">1 open review</p><h2 className="mt-2 text-xl font-semibold">Vintage camera lens</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">The delivery window passed after dispatch. Submit evidence so a mediator can review the transaction fairly.</p></div><LifeBuoy className="size-6 shrink-0 text-amber-300" /></div><button onClick={onOpen} className="mt-5 h-10 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground">Open dispute center</button></div><div className="rounded-2xl border border-border bg-card p-5"><h3 className="text-sm font-semibold">How disputes work</h3><div className="mt-4 grid gap-3 sm:grid-cols-3">{['Submit evidence','Both sides respond','Mediator decides'].map((step, index) => <div key={step} className="rounded-xl bg-muted/50 p-4"><span className="text-xs text-primary">0{index + 1}</span><p className="mt-2 text-xs font-medium">{step}</p></div>)}</div></div></div> }
function Metric({ label, value, note, icon: Icon, positive }: { label: string; value: string; note: string; icon: typeof Wallet; positive?: boolean }) { return <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-medium text-muted-foreground">{label}</p><span className="grid size-7 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4" /></span></div><p className="mt-4 text-2xl font-semibold tracking-tight">{value}</p><p className={`mt-1 text-[11px] ${positive ? 'text-emerald-300' : 'text-muted-foreground'}`}>{note}</p></div> }
function Field({ label, value, onChange, placeholder, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; placeholder: string; type?: string }) { return <label className="block text-left"><span className="text-xs font-medium text-muted-foreground">{label}</span><input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="mt-2 h-11 w-full rounded-xl border border-border bg-muted/40 px-3 text-sm outline-none focus:border-primary" /></label> }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-background/75 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><button onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Close dialog"><X className="size-4" /></button></div>{children}</div></div> }

export const dynamic = 'force-dynamic'
